function config = generateConfigStructIR()
% Create the overall structure
config = struct();
% The autoaligner aligns in sections, each containing multiple cameras
config.B0B1IR = struct('name', 'B0 and B1 IR', ...
                     'feedbackOnPV', 'SIOC:SYS1:ML01:AO181', ...
                     'gainPV', 'SIOC:SYS1:ML01:AO198', ...
                     'nShotsAveraged', 3, ...
                     'calibrationMatrixPath', '/home/fphysics/cemma/S20Laser/S20LaserAlignmentFeedback/cal_matrix_S20TransportB0B1IR11_30_2021_18_22.mat', ...
                     'cameras', struct());

% In each section there are cameras
B0 = struct('cameraPV', 'CAMR:LT20:202', ...
            'motorPVHorizontal', 'MOTR:LI20:MC06:S1:CH1:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC06:S1:CH2:MOTOR', ...
            'target', [755, 438]);
B1 = struct('cameraPV', 'CAMR:LT20:203', ...
            'motorPVHorizontal', 'MOTR:LI20:MC06:S1:CH4:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC06:S1:CH3:MOTOR', ...
            'target', [420.9, 490.9]);
config.B0B1IR.cameras.B0 = B0;
config.B0B1IR.cameras.B1 = B1;

end
