function config = generateConfigStruct()
% Create the overall structure
config = struct();
% The autoaligner aligns in sections, each containing multiple cameras
config.pulsePickerRegenOut = struct('name', 'Pulse Picker and Regen Out', ...
                                    'feedbackOnPV', 'SIOC:SYS1:ML01:AO170', ...
                                    'gainPV', 'SIOC:SYS1:ML01:AO190', ...
                                    'nShotsAveraged', 3, ...
                                    'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/displays/../config/calMatrices/calMatrix_pulsePickerRegenOut.txt', ...
                                    'cameras', struct());
config.preampNearFar = struct('name', 'Preamp Near and Far', ...
                              'feedbackOnPV', 'SIOC:SYS1:ML01:AO171', ...
                              'gainPV', 'SIOC:SYS1:ML01:AO191', ...
                              'nShotsAveraged', 3, ...
                              'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/displays/../config/calMatrices/calMatrix_preampNearFar.txt', ...
                              'cameras', struct());
config.mainampNearFar = struct('name', 'Mainamp Near and Far', ...
                               'feedbackOnPV', 'SIOC:SYS1:ML01:AO172', ...
                               'gainPV', 'SIOC:SYS1:ML01:AO199', ...
                               'nShotsAveraged', 10, ...
                               'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/displays/../config/calMatrices/calMatrix_mainampNearFar.txt', ...
                               'cameras', struct());
config.DMNearFar = struct('name', 'DM Near and Far', ...
                          'feedbackOnPV', 'SIOC:SYS1:ML01:AO180', ...
                          'gainPV', 'SIOC:SYS1:ML01:AO186', ...
                          'nShotsAveraged', 3, ...
                          'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/displays/../config/calMatrices/calMatrix_DMNearFar.txt', ...
                          'cameras', struct());
config.HeNeNearFar = struct('name', 'HeNe Near and Far', ...
                     'feedbackOnPV', 'SIOC:SYS1:ML01:AO173', ...
                     'gainPV', 'SIOC:SYS1:ML01:AO192', ...
                     'nShotsAveraged', 3, ...
                     'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/config/calMatrices/calMatrix_HeNeNearFar.txt', ...
                     'cameras', struct());
config.B0B1 = struct('name', 'B0 and B1', ...
                     'feedbackOnPV', 'SIOC:SYS1:ML01:AO174', ...
                     'gainPV', 'SIOC:SYS1:ML01:AO193', ...
                     'nShotsAveraged', 3, ...
                     'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/config/calMatrices/calMatrix_B0B1.txt', ...
                     'cameras', struct());
config.B2B3 = struct('name', 'B2 and B3', ...
                     'feedbackOnPV', 'SIOC:SYS1:ML01:AO175', ...
                     'gainPV', 'SIOC:SYS1:ML01:AO194', ...
                     'nShotsAveraged', 3, ...
                     'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/config/calMatrices/calMatrix_B2B3.txt', ...
                     'cameras', struct());
config.B4 = struct('name', 'B4', ...
                   'feedbackOnPV', 'SIOC:SYS1:ML01:AO176', ...
                   'gainPV', 'SIOC:SYS1:ML01:AO195', ...
                   'nShotsAveraged', 3, ...
                   'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/config/calMatrices/calMatrix_B4.txt', ...
                   'cameras', struct());
config.B5 = struct('name', 'B5', ...
                   'feedbackOnPV', 'SIOC:SYS1:ML01:AO177', ...
                   'gainPV', 'SIOC:SYS1:ML01:AO196', ...
                   'nShotsAveraged', 3, ...
                   'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/config/calMatrices/calMatrix_B5.txt', ...
                   'cameras', struct());
config.B6 = struct('name', 'B6', ...
                   'feedbackOnPV', 'SIOC:SYS1:ML01:AO178', ...
                   'gainPV', 'SIOC:SYS1:ML01:AO197', ...
                   'nShotsAveraged', 3, ...
                   'calibrationMatrixPath', '/home/fphysics/rariniel/pydm/user-facet/config/calMatrices/calMatrix_B6.txt', ...
                   'cameras', struct());
% In each section there are cameras
S20RegenOut = struct('cameraPV', 'CAMR:LT20:100', ...
                     'motorPVHorizontal', 'MOTR:LI20:MC06:S3:CH3:MOTOR', ...
                     'motorPVVertical', 'MOTR:LI20:MC06:S3:CH4:MOTOR', ...
                     'target', [606, 526]);
S20PulsePicker = struct('cameraPV', 'CAMR:LT20:101', ...
                        'motorPVHorizontal', 'MOTR:LI20:MC06:S3:CH1:MOTOR', ...
                        'motorPVVertical', 'MOTR:LI20:MC06:S3:CH2:MOTOR', ...
                        'target', [650, 379]);
config.pulsePickerRegenOut.cameras.S20RegenOut = S20RegenOut;
config.pulsePickerRegenOut.cameras.S20PulsePicker = S20PulsePicker;

S20PreampNear = struct('cameraPV', 'CAMR:LT20:102', ...
                     'motorPVHorizontal', 'MOTR:LI20:MC06:M0:CH1:MOTOR', ...
                     'motorPVVertical', 'MOTR:LI20:MC06:M0:CH2:MOTOR', ...
                     'target', [740.53, 345.6]);
S20PreampFar = struct('cameraPV', 'CAMR:LT20:103', ...
                        'motorPVHorizontal', 'MOTR:LI20:MC06:M0:CH3:MOTOR', ...
                        'motorPVVertical', 'MOTR:LI20:MC06:M0:CH4:MOTOR', ...
                        'target', [644, 353.8]);
config.preampNearFar.cameras.S20PreampNear = S20PreampNear;
config.preampNearFar.cameras.S20PreampFar = S20PreampFar;

S20MainampNear = struct('cameraPV', 'CAMR:LT20:105', ...
                     'motorPVHorizontal', 'MOTR:LI20:MC06:S6:CH1:MOTOR', ...
                     'motorPVVertical', 'MOTR:LI20:MC06:S6:CH2:MOTOR', ...
                     'target', [555, 263]);
S20MainampFar = struct('cameraPV', 'CAMR:LT20:106', ...
                        'motorPVHorizontal', 'MOTR:LI20:MC06:S6:CH3:MOTOR', ...
                        'motorPVVertical', 'MOTR:LI20:MC06:S6:CH4:MOTOR', ...
                        'target', [424, 265]);
config.mainampNearFar.cameras.S20MainampNear = S20MainampNear;
config.mainampNearFar.cameras.S20MainampFar = S20MainampFar;

DMNear = struct('cameraPV', 'CAMR:LT20:108', ...
                'motorPVHorizontal', 'MOTR:LI20:MC06:S2:CH2:MOTOR', ...
                'motorPVVertical', 'MOTR:LI20:MC06:S2:CH1:MOTOR', ...
                'target', [540, 500]);
DMFar = struct('cameraPV', 'CAMR:LT20:109', ...
               'motorPVHorizontal', 'MOTR:LI20:MC06:S2:CH3:MOTOR', ...
               'motorPVVertical', 'MOTR:LI20:MC06:S2:CH4:MOTOR', ...
               'target', [900, 300]);
config.DMNearFar.cameras.DMNear = DMNear;
config.DMNearFar.cameras.DMFar = DMFar;

HeNeNear = struct('cameraPV', 'CAMR:LT20:200', ...
            'motorPVHorizontal', 'MOTR:LI20:MC06:S4:CH1:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC06:S4:CH2:MOTOR', ...
            'target', [672, 489]);
HeNeFar = struct('cameraPV', 'CAMR:LT20:201', ...
            'motorPVHorizontal', 'MOTR:LI20:MC06:S4:CH3:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC06:S4:CH4:MOTOR', ...
            'target', [666.5, 510]);
config.HeNeNearFar.cameras.HeNeNear = HeNeNear;
config.HeNeNearFar.cameras.HeNeFar = HeNeFar;

B0 = struct('cameraPV', 'CAMR:LT20:202', ...
            'motorPVHorizontal', 'MOTR:LI20:MC06:S5:CH1:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC06:S5:CH2:MOTOR', ...
            'target', [755, 438]);
B1 = struct('cameraPV', 'CAMR:LT20:203', ...
            'motorPVHorizontal', 'MOTR:LI20:MC06:S5:CH4:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC06:S5:CH3:MOTOR', ...
            'target', [420.9, 490.9]);
config.B0B1.cameras.B0 = B0;
config.B0B1.cameras.B1 = B1;

B2 = struct('cameraPV', 'CAMR:LT20:204', ...
            'motorPVHorizontal', 'MOTR:LI20:MC07:M0:CH2:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC07:M0:CH1:MOTOR', ...
            'target', [595.2, 500]);
B3 = struct('cameraPV', 'CAMR:LT20:205', ...
            'motorPVHorizontal', 'MOTR:LI20:MC07:M0:CH4:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC07:M0:CH3:MOTOR', ...
            'target', [499, 482]);
config.B2B3.cameras.B2 = B2;
config.B2B3.cameras.B3 = B3;

B4 = struct('cameraPV', 'CAMR:LT20:206', ...
            'motorPVHorizontal', 'MOTR:LI20:MC07:S1:CH2:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC07:S1:CH1:MOTOR', ...
            'target', [302, 103]);
config.B4.cameras.B4 = B4;

B5 = struct('cameraPV', 'CAMR:LT20:207', ...
            'motorPVHorizontal', 'MOTR:LI20:MC08:M0:CH4:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC08:M0:CH3:MOTOR', ...
            'target', [593, 432]);
config.B5.cameras.B5 = B5;

B6 = struct('cameraPV', 'CAMR:LT20:208', ...
            'motorPVHorizontal', 'MOTR:LI20:MC08:S2:CH2:MOTOR', ...
            'motorPVVertical', 'MOTR:LI20:MC08:S2:CH1:MOTOR', ...
            'target', [321, 230]);
config.B6.cameras.B6 = B6;
end
